default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['BD_LOCAL_USER'] %>
  password: <%= ENV['BD_LOCAL_PASSWORD'] %>

development:
  <<: *default
  database: apisconror_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: apisconror_test
  host: localhost
  port: 5432


production:
  <<: *default
  database: apisconror_production
  username: apisconror
  password: <%= ENV['APISCONROR_DATABASE_PASSWORD'] %>
